"""empty message

Revision ID: 20a657ca50d8
Revises: ca7b8278a322
Create Date: 2019-04-11 09:56:30.666771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20a657ca50d8'
down_revision = 'ca7b8278a322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('tags', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
