"""empty message

Revision ID: 8b96bdff01b2
Revises: ac5e9b998f4d
Create Date: 2019-04-10 10:14:06.669062

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b96bdff01b2'
down_revision = 'ac5e9b998f4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'article_ibfk_1', 'article', type_='foreignkey')
    op.create_foreign_key(None, 'article', 'user', ['user_id'], ['id'])
    op.drop_column('article', 'author_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.create_foreign_key(u'article_ibfk_1', 'article', 'user', ['author_id'], ['id'])
    op.drop_column('article', 'user_id')
    # ### end Alembic commands ###
