"""empty message

Revision ID: dfcccfb8b0c4
Revises: 20a657ca50d8
Create Date: 2019-04-11 10:22:00.778420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dfcccfb8b0c4'
down_revision = '20a657ca50d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Article_tag',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'tag_id')
    )
    op.drop_table('article_tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_tag',
    sa.Column('article_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], [u'article.id'], name=u'article_tag_ibfk_1'),
    sa.ForeignKeyConstraint(['tag_id'], [u'tag.id'], name=u'article_tag_ibfk_2'),
    sa.PrimaryKeyConstraint('article_id', 'tag_id'),
    mysql_default_charset=u'utf8mb4',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('Article_tag')
    # ### end Alembic commands ###
